
###
GET http://localhost:3001/characters

###
POST http://localhost:3001/characters
content-type: application/json

{
    "id": "alhaitham",
    "startLvL": 3,
    "startIsAscended": false,
    "endLvL": 20,
    "endIsAscended": true
}

###
DELETE http://localhost:3001/characters
content-type: application/json

{
    "id": "alhaitham"
}

###
GET http://localhost:3001/characters/resources?id=alhaitham&startLvL=3&startIsAscended=false&endLvL=20&endIsAscended=true
content-type: application/json
